### ISSUE TITLE
write speed is too slow

### ISSUE THREAD

**Issue by whynames** [Luca3317/TMPEffects#7]
Hey, write delay is too slow for me even when I adjust it too 0.000001f. Is there a turn around for speeding it up?

**Comment by Luca3317** [comment]
Hi, its most likely because the delay speed is bottlenecked by your framerate. TMPWriter's coroutine uses WaitForSeconds to wait for the delays and doesnt account for additional time that passed during the frame.

This is an issue I hadnt considered yet, Ill push a version of the TMPWriter with this fixed into the WorkingChanges branch later today.

**Comment by Luca3317** [comment]
Issue should be fixed, Ill merge it onto main in a few days (once i fixed an annoying little bug with command tag indices). For now you can grab it from WorkingChanges if you want to.

For 0.000001 seconds delay it will ofc all just appear in one frame, unless youre running at a million frames 😮
